// Class automatically generated by Dev-C++ New Class wizard

#ifndef TRAZA_H
#define TRAZA_H

#include <stdio.h>
#include <string.h>
#include <time.h>
#include <string>
#include "constant.h"
#include "tcstring.h"
#include <limits.h>
#include <iostream>


using namespace std;
/*
 * Clase para generar trazas
 */
class Traza
{
	public:
		// class constructor
        Traza(const char *ruta);
		 Traza();
		// class destructor
		~Traza();
  	     static void print(const char *, int, int); //Pinta el mensaje en la traza
//		 static void print(const char *,const char *, int);
		 static void print(const char *, int);
		 static void print(string, string, int);
		 static void setTraza(bool);
		 static void setConsole(bool);

    private:
         static FILE *fout;
  	     static bool isConsole;
  	     static bool pintarTrazas;

  	     char ruta[PATH_MAX];
  	     void iniFile();
  	     void closeFile();
};

#endif // TRAZA_H
